FROM balenalib/%%BALENA_MACHINE_NAME%%-debian
#-python:3.9

RUN install_packages dnsmasq wireless-tools

# For the custom app

RUN apt-get update \
    && apt-get install -y python3-pip python3-dev python3-psutil bluez bluez-hcidump sudo

WORKDIR /usr/src/app

COPY app/requirements.txt .
COPY app/reporter.py .
COPY app/influxdb2_reporter.py .
COPY app/config.py .
COPY app/app.py .
 
RUN python3 -m pip install --no-cache-dir -r requirements.txt

CMD ["python3", "app.py"]
